# Default compose file for development and production.
# Should be used directly in development.
# Automatically loads `docker-compose.override.yml` if it exists.
# No extra steps required.

version: "3.6"
services:
  download_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python server.py --logs
