version: "3.6"
services:
  download_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
      ports:
        - "8080:8080"
    command: python server.py --logs
